export type UpdateMotoristDtoReq = {
  module?: string;
  company?: string;
  name?: string;
  email?: string;
  phone?: string;
  cpf?: string;
  date_birth?: string;
  gender?: string;
  password?: string;
  zipcode?: string;
  address?: string;
  neighborhood?: string;
  state?: string;
  city?: string;
  car_plate?: string;
  car_renamed?: string;
  model?: string;
  year?: string;
  color?: string;
};
